### ISSUE TITLE
Editing task in Safari on macOS not possible

### ISSUE THREAD

**Issue by marbetschar** [onejgordon/flow-dashboard#101]
As soon as I click on the edit icon in macOS Safari to edit a given task it gets marked as "done" - and the opening menu changes.

It is not possible to edit any given task without mark it as "done".

**Comment by onejgordon** [comment]
This is a problem with the material-ui library: https://github.com/mui-org/material-ui/issues/3113 Will be fixed once the new material-ui v1 comes out of beta.

For now, this issue remains in Safari (though no issue in Chrome/Firefox).
