### ISSUE TITLE
Better installation documentation

### ISSUE THREAD

**Issue by LukeStaszewski** [onejgordon/flow-dashboard#134]
Hello!

I'd love to start contributing to this project but unfortunately I can't even seem to get it installed :(

I think maybe the best way I can start helping out is by improving the documentation! I would love to add in some extra info and different problems people might encounter.

I will post issues here so they can be answered individually, but I was wondering if it would be possible for someone to hop on a screenshare with me to sort out the issues Im currently having as I'm not even sure how to describe them? Then I can make notes - and update the docs with further explanation for anyone who is facing the same issues 

Let me know your thoughts on this :)

**Comment by onejgordon** [comment]
@LukeStaszewski happy to jump on a call to debug some issues. Let's coordinate by email.
