### ISSUE TITLE
'Failed To Validate' Error On Deployed App

### ISSUE THREAD

**Issue by markedconfidential** [onejgordon/flow-dashboard#135]
What should I be taking a look at to figure out what's causing the below error after I've gotten the app up and running on GCP?

![Screen Shot 2020-06-06 at 4 08 31 PM](https://user-images.githubusercontent.com/64333124/83953680-290ecb80-a810-11ea-8411-ff6dd878a24d.png)

**Comment by markedconfidential** [comment]
Figured it out — thought the Client ID needed to have the "apps.googleusercontent.com" stripped out before dropping into secrets.py based on some outdated Google documentation.

**Comment by onejgordon** [comment]
Glad you got it sorted.
