### ISSUE TITLE
Birthday selection should allow for manual entry (text fields)

### ISSUE THREAD

**Issue by kfrz** [onejgordon/flow-dashboard#26]
On the `app/timeline` page, the datepicker is pretty slick but I don't want to click ~`12 * $my_age*` times, as the default calendar opens to today, to get to my birthday.   This should be made an optional input method and the primary method should be able to be entered via manual text entry.

**Comment by onejgordon** [comment]
Thanks for this. I agree on text entry, but do note that the material-ui datepicker widget allows year selection via clicking the year in the upper left corner. Not a particularly intuitive UI, but at least an improvement on `12*age` clicks.

<img width="334" alt="screen shot 2017-05-07 at 1 22 50 am" src="https://cloud.githubusercontent.com/assets/57584/25776316/d114df4c-32c3-11e7-9785-320bce3aa5a6.png">

**Comment by kfrz** [comment]
Thanks for pointing that out, it didn't work well on my laptop I'll try again
