### ISSUE TITLE
Adding new habits is difficult

### ISSUE THREAD

**Issue by dsbert** [onejgordon/flow-dashboard#28]
The initial habit creation wizard through the dashboard works well. However, adding more habits later requires you to go into the settings. It also does not present you with the same color picker that the initial habit set up did.

**Comment by timpulver** [comment]
Agree, I was missing a «New Habit»-button to easily add another second habit.

**Comment by onejgordon** [comment]
Thank you -- been meaning to do this!

**Comment by onejgordon** [comment]
More convenient 'new habit' menu option will be out shortly.
