### ISSUE TITLE
unable to authenticate google fit 

### ISSUE THREAD

**Issue by iabhatti** [onejgordon/flow-dashboard#40]
I'm able to create an account using using Google just fine. When I try to authenticate the Google Fit, I'm prompted to select my Google account and then asked to allow Flow to have the relevant permissions, but upon clicking "allow" I'm given the following error:

{"message": "Unauthorized", "success": false}

**Comment by onejgordon** [comment]
I believe this is fixed in https://github.com/onejgordon/flow-dashboard/commit/3269ce0c007309e4cba77f3347f5e0c05e7723d0, let me know if you're still experiencing the problem
