### ISSUE TITLE
Goals are not easy to enter using Firefox for Android

### ISSUE THREAD

**Issue by JonTheNiceGuy** [onejgordon/flow-dashboard#46]
All you can see is the "Goal 1" line, and you can't hit submit.

**Comment by onejgordon** [comment]
In general dialog boxes in Flow are tough to use on mobile devices. Let me look into how to improve on that.

**Comment by onejgordon** [comment]
Style updates don't seem to have cleared the issue fully.  Related to https://github.com/callemall/material-ui/issues/3295

**Comment by onejgordon** [comment]
Looks like https://github.com/onejgordon/flow-dashboard/commit/ed2be553479b8c392305b7d4743ba7a74dcabd82 fixed mobile dialogs on Chrome/Firefox.
