### ISSUE TITLE
Data is not being loaded on server restart

### ISSUE THREAD

**Issue by mtmarsh2** [onejgordon/flow-dashboard#50]
Any idea why this would be happening? Was working until I restarted my server, and not the flow dashboard loads with no habits or data. Does something else need to be running besides just `./scripts/server.sh`

**Comment by onejgordon** [comment]
You need to run gulp in another terminal to build JS files, in case there were any changes.

Did you run `./scripts/server.sh` with the clean flag? If so, that would clear the datastore.

Can you confirm if your data appears in the dev server's console? Access it from `http://localhost:8000/datastore`.

**Comment by mtmarsh2** [comment]
Hi @onejgordon ,

Thanks for the response. I didn't run it with the clean flag (just ran with `./scripts/server.sh`). I did look at the datastore locally through `http://localhost:8000/datastore` and saw that none of the data was there, in the viewer tab. I then tried saving a habit now, to confirm that new data appears there and it did, so I'm thinking the data must have been deleted from before? 

Is there a local copy of the data that I could check, like a `.sql` file, or is it all stored on Google Cloud? I'm unfamiliar with Google App engine in general.

**Comment by onejgordon** [comment]
If you're running on the local dev server, then all data is stored in a tmp file on your machine. See this answer: http://stackoverflow.com/questions/3588817/where-is-my-local-app-engine-datastore

The dev server is meant for development and not actual application usage since nothing is persistent locally. If you want to run your own instance of Flow, you'll want to deploy to a GCP project which I have some instructions for in the readme.  

Docs on GCP's app engine dev server:
https://cloud.google.com/appengine/docs/standard/python/tools/using-local-server

**Comment by mtmarsh2** [comment]
Oh I see, so running `scripts/server.sh` would run `dev_appserver.py` without the datastore path, which means it would be set to somewhere in `/tmp` on a Mac right? that would explain why restarting would make it disappear, since `/tmp` would get cleared on restart.

I did enter the credentials for a GCP project in the different settings files, but maybe it didn't use that? If the GCP project creds weren't configured correctly, would it default to saving data locally?

**Comment by onejgordon** [comment]
Yep, that makes sense.

Entering the GCP credentials is fine, but you have to deploy (push to cloud) to run your application in a production environment, and on the internet (e.g. [your-app-id].appspot.com). GAE isn't set up for real local-only usage.

See https://github.com/onejgordon/flow-dashboard#deploy. It's just 1 command you need to run to push your app to GCP.

**Comment by mtmarsh2** [comment]
Cool I will try that, thanks for the help!
