### ISSUE TITLE
Add a pomodoro timer to the dashboard

### ISSUE THREAD

**Issue by Circuit8** [onejgordon/flow-dashboard#52]
Would be great to include a pomodoro timer with the app. You could then set targets for how many aught to be completed in a week. It's an invaluable tool in aiding productivity. A fairly good open source implementation of a pomodoro tracker named [tomato.es](http://www.tomato.es/) could serve as inspiration.

**Comment by onejgordon** [comment]
I've been thinking about this too. Would you link it to tasks -- which we are planning on optionally linking to projects -- or have it remain separate?

**Comment by Circuit8** [comment]
Well I think for sure there should be a count for each day, that you could see on a graph. Linking to tasks is a great idea, but perhaps keep that link optional. Another idea is just to have them optionally link to projects. I think any combination has its pros and cons.

**Comment by onejgordon** [comment]
I'm working on an implementation. Though I designed tasks to be used to track the most important few items of work on a given day, I believe they should be generic enough to capture any work items / todos of any kind, including those that you might want to focus on with pomodoro sessions. I think this will be flexible once tasks are able to be optionally linked to projects as well.

I'm not convinced this is the right strategy, but I also don't think a dedicated Pomodoro model makes sense. If timing and pomodoro sessions are stored within a task, then the task chart can be expanded to optionally plot minutes of work, # of pomodoro sessions, or just boolean completion (as is currently the case) on a task by task basis.

Thoughts?

<img width="1009" alt="screen shot 2017-05-25 at 4 15 12 pm" src="https://cloud.githubusercontent.com/assets/57584/26451675/b81f6f1a-4165-11e7-9195-7258555d61db.png">

In this design, when the user chooses to mark a task as WIP, the overlay at bottom appears. It has play/pause/reset/stop controls, the count-up timer, and an option to set a target (pomodoro) of 25 minutes, after which a notification is shown. When stop is pressed, the timer is logged to the task, so the total duration of work in seconds accumulates.

**Comment by Circuit8** [comment]
I think this is a fantastic design, great stuff
