### ISSUE TITLE
Visualize journal tags on main journal analysis chart

### ISSUE THREAD

**Issue by Circuit8** [onejgordon/flow-dashboard#53]
Would be great to add tags to journal entries. This way you can analyse the impact that certain things in your life have on your happiness levels.

For example, you could tag a day with 'exercise', then when you view your chart showing your daily satisfaction over time it could label the days with the exercise tag. Then you could see if your daily satisfaction was impacted positively / negatively by that tag.

This would be great for running experiments with your daily routine.

**Comment by onejgordon** [comment]
Hey @Circuit8, tagging journal entries is actually supported. When configuring your journal questions (Settings -> Daily Journals), make sure to enable '@mentions and #hashtags'.

<img width="425" alt="screen shot 2017-05-23 at 10 59 06 am" src="https://cloud.githubusercontent.com/assets/57584/26344057/f7cfd228-3fa6-11e7-861c-44ba1fe0d0c6.png">

Once that's done, you'll be able to enter people and tags in those journal questions. Then, once you have journal data that's got tags, you can segment by tag, as I believe you are hoping to:

<img width="1046" alt="screen shot 2017-05-23 at 11 01 16 am" src="https://cloud.githubusercontent.com/assets/57584/26344122/33bd4c70-3fa7-11e7-946d-172a08e60812.png">

Let me know if this is what you were looking for.

**Comment by Circuit8** [comment]
Hey thats great I didn't realize that was possible. 
Seeing the results segmented by a tag is great, but what I was thinking was having a vertical line on the main graph of a certain colour associated with a tag, or possibly a little icon under the y axis on that date. If you see what I mean? Then you could select which tags to display on the graph, (all switched off by default). This way you can see the effect of tags over time.

**Comment by onejgordon** [comment]
I like the idea of choosing the tags you want to highlight, and then being able to see them on the main chart, perhaps by highlighting the points on the chart, or an icon below the x-axis.
