### ISSUE TITLE
Javascript origin mismatch (Google Oauth client ID configuration)

### ISSUE THREAD

**Issue by abhi18av** [onejgordon/flow-dashboard#56]
Hi @onejgordon ,

I've been hacking at this for a while now, lately I'm getting this error upon the reload of the app on the local server 
```
Failed to initialize Google Client -- Check that 'block third-party cookies and site data' is not enabled.
```

Also, the sidebar menu options aren't there at all.
![screenshot from 2017-05-23 12-21-58](https://cloud.githubusercontent.com/assets/12799326/26341664/8530c73e-3fb2-11e7-9d08-a627f1a1068e.png)

Perhaps this has to do something with the local settings or the configuration on the Google Dev. Dashboard. Mmmm, I'm stuck :)

**Comment by onejgordon** [comment]
Hi @abhi18av. In the screenshot, it looks like you're not signed in. What happens when you try to sign in? The error you noted occurs when there's a problem loading the Google JS API, which is a known issue in Chrome and Firefox when the browser setting `block third-party cookies and site data` is enabled. Can you confirm this setting is not enabled in your browser?

**Comment by abhi18av** [comment]
So, I've checked both the firefox and chromium versions here. It's not the problem it seems.

![screenshot from 2017-05-23 13-11-29](https://cloud.githubusercontent.com/assets/12799326/26343362/609d2604-3fb9-11e7-9331-751b5423149f.png)

**Comment by abhi18av** [comment]
And you guessed correctly earlier, I'm unable to sign in via Google.

![screenshot from 2017-05-23 13-14-06](https://cloud.githubusercontent.com/assets/12799326/26343511/e291bce2-3fb9-11e7-902e-89bfde9eb85b.png)

@onejgordon , isn't there some admin password setting for local dev?

**Comment by onejgordon** [comment]
The error states a JS origin mismatch in the client ID you configured in GCP. Did you create the client ID and add localhost as a valid origin? I realized that the instructions on this were incomplete, see: https://github.com/onejgordon/flow-dashboard/commit/40e428ba3428b7e9dc70c2d8ed48b92d4928597c

**Comment by onejgordon** [comment]
Please re-open if this issue isn't solved

**Comment by abhi18av** [comment]
Hello @onejgordon , 

Is any work being done towards this Docker image? I'm really looking forward to play with `flow` in a hassle free environment :)
