### ISSUE TITLE
Sign out problem

### ISSUE THREAD

**Issue by vvai** [onejgordon/flow-dashboard#62]
When user have signed out and tries to open dashboard [link](https://flowdash.co/app/dashboard) (for example from bookmarks) he or she sees blank page and there are some errors in console
![image](https://cloud.githubusercontent.com/assets/7115235/26562019/7c1ed078-44cb-11e7-8b37-9b84b445e04c.png)

**Comment by vvai** [comment]
The problem is reproducible at least in Chrome and Safari, but I think that in any other browser also

**Comment by onejgordon** [comment]
Thanks for filing this -- I can reproduce and will work on a fix.

**Comment by onejgordon** [comment]
Should be fixed by https://github.com/onejgordon/flow-dashboard/commit/28114ed13116e2939b30a714b60f176803668965
