### ISSUE TITLE
Added questions to daily journal disappear 

### ISSUE THREAD

**Issue by shaansheikh** [onejgordon/flow-dashboard#63]
I have added additional questions to my daily journal entry multiple times via the settings tab, but after a day or so they always disappear

**Comment by onejgordon** [comment]
@shaansheikh sorry you're having this issue. I haven't been able to reproduce it, is there any more information you can provide on what you've noticed?

When adding new questions, I just want to confirm you're saving the settings changes after adding new questions using the button in the bottom left.

<img width="1212" alt="screen shot 2017-05-30 at 8 05 52 pm" src="https://cloud.githubusercontent.com/assets/57584/26595259/85f84374-4573-11e7-99f6-ebcfc806e93a.png">

**Comment by shaansheikh** [comment]
Yes, I am saving the settings, and the questions do show up in my jornal entries for a day or two. Will try to experiment more when I have time to narrow down when/why they disappear

**Comment by shaansheikh** [comment]
Update: I have noticed that when I have added those questions again, the dashboard was able to find my responses to them for previous jornal entries. Even though it does not remember the questions, it remembers my responses

**Comment by onejgordon** [comment]
Flow stores responses keyed by the 'variable name' you set in the settings for each question, so it makes sense that you're able to view historical responses once the questions are restored.

Has this issue happened again? I can't reproduce this, or think of any possible scenario that would result in clearing questions.

**Comment by onejgordon** [comment]
If this re-occurs reproducibly, please re-open.
