### ISSUE TITLE
Making editing habit easier 

### ISSUE THREAD

**Issue by Tabrizian** [onejgordon/flow-dashboard#65]
Hi, 
Thanks for your really perfect platform. There is only one problem I think with it. You can't edit things after they are created very much. For example, after you create a task you can't edit it's title. Or after you create a habit you can't change the goal of it.

**Comment by onejgordon** [comment]
Hi @Tabrizian, thanks for this feedback, you're right that editing habits isn't convenient currently.

If you need to, it is currently possible to edit habits from the settings page -> habits. We'll work on a more convenient method for this in this issue.

**Comment by Tabrizian** [comment]
Thanks @onejgordon. But your way of organizing life is unique.

Thanks for your platform.

**Comment by onejgordon** [comment]
It's now possible to edit habits in the dashboard -- Click on the habit title, then edit in the dialog window that appears

**Comment by Tabrizian** [comment]
Perfect. I really appreciate it @onejgordon. :100:
