### ISSUE TITLE
Won't allow sign-in on Google Chrome

### ISSUE THREAD

**Issue by lemonfox** [onejgordon/flow-dashboard#87]
Only tested on latest version of Google Chrome. 

Went to sign-in page, clicked sign-in button, and was prompted with a new window for Google account sign-in. Upon choosing the Google account to sign-in with, the prompt window closes and nothing happens.

**Comment by onejgordon** [comment]
Could it be the same chrome setting referenced in this issue? https://github.com/onejgordon/flow-dashboard/issues/34
