### ISSUE TITLE
Journal questions of type number show a slider

### ISSUE THREAD

**Issue by xverges** [onejgordon/flow-dashboard#89]

**Comment by onejgordon** [comment]
True, this was a lazy design shortcut -- @xverges, preferable would be, open-ended numeric input?

**Comment by xverges** [comment]
> open-ended numeric input?

I think that it would cover the more general case, wouldn't it?

In my particular case I want to rate myself in a 1 to 4 scale [in several dimensions](http://www.marshallgoldsmith.com/articles/questions-that-make-a-difference-the-daily-question-process/) and the current 1 to 10 slider causes unnecessary struggle for me about it being a 6 or an 8 :-) Thus, an entry field (or a set of labels?) would save me time and (small) worries

**Comment by onejgordon** [comment]
Great, I've done this as a new response type: "Number (Free Input Box)" to keep things backwards compatible for those using the previous 'number' type but preferring the slider.

Thanks for sharing that daily questions article as well, @xverges

**Comment by xverges** [comment]
UI worked like a charm when writing the journal. 

However, on the Journal history, I get `N/A`s after 
https://flowdash.co/api/journal?before_date=2017-09-20&days=10 
returns what looks like proper JSON

This is what I see when I use _inspect element_
```
<label>Did I do my best to be happy (1-4)?</label>
<!-- react-text: 7599 -->
N/A
<!-- /react-text -->
```

**Comment by onejgordon** [comment]
Good catch (journal rendering UI oversight). A fix should now be live.

**Comment by xverges** [comment]
Awesome! Thanks!
