### ISSUE TITLE
More than 10 habits

### ISSUE THREAD

**Issue by AndreiBarsan** [onejgordon/flow-dashboard#95]
It would be nice if more than 10 habits could be tracked.

I feel like it's really easy to fill up the list and still have many more to add (easy, generic-ish example: (0) eat well, (1) meditate, (2) exercise, (3) call parents, (4) read book, (5) read scientific paper, (6) no alcohol, (7) eat fruit, (8) wake up before 9am, (9) no technology 1h before bed, (10!) track time, (11!) practice ping-pong, etc.).

Is there a particular design reason why the number of habits is limited?

**Comment by onejgordon** [comment]
Updated max active habits to 20 in the latest release.
